name: foodlink
description: "Une plateforme de dons alimentaires géolocalisés qui met en relation donateurs et bénéficiaires"
publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: '>=3.0.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter

  # Firebase
  firebase_core: ^2.32.0
  firebase_auth: ^4.20.0
  cloud_firestore: ^4.17.0
  firebase_storage: ^11.7.0
  firebase_messaging: ^14.9.0
  
  # Notifications
  # flutter_local_notifications: ^16.3.2
  
  # State Management
  provider: ^6.1.1
  
  # UI Components
  cupertino_icons: ^1.0.2
  google_fonts: ^6.1.0
  
  # Maps & Location
  google_maps_flutter: ^2.5.0
  geolocator: ^10.1.0
  geocoding: ^2.1.1
  
  # Image handling
  image_picker: ^1.0.4
  cached_network_image: ^3.3.0
  
  # Utilities
  intl: ^0.20.2
  uuid: ^4.2.1
  shared_preferences: ^2.2.2
  permission_handler: ^11.1.0
  path_provider: ^2.1.1
  crypto: ^3.0.3
  
  # HTTP & Networking
  http: ^1.1.0
  
  # Additional dependencies
  google_sign_in: ^6.1.5
  url_launcher: ^6.2.1
  
dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true
  
  assets:
    - assets/images/donations/